### PR TITLE
Merging the CMS Application in Authentication with the Complete Application

### PR DESCRIPTION
**Pull request by danielgerardclaassen**
This pull request aims to merge the CMS application with the complete application. The changes included in the first and only commit of Integrate are:

-Added 'files' folder used by CMS application to store uploaded files
-Added 'views' folder which contains several ejs files, which is the viewmodel used by the CMS
-Modifed the 'package.json' file to contain the necessary modules to support the CMS
-Added 'passport-config.js' which is a necessary file used by the encryption method contained in the passport module
-Modified the README to contain information on the CMS, and to make instructions more compatible with the landing page we have
-Added the routing used by the CMS application into 'server.js' as well as the necessary module calls and viewmodel establishments
-Altered the textual description accompanying the test model, just fixing a bit of the english sorry Song! Haha.

There are no real structural changes to the code present in the master base. Nearly all of the code are additions from the Authentication branch.

If this pull request is accepted, the CMS, Authentication, and Integrate branches will become obsolete, and can be safely deleted. This will also allow further development to be done on a single base as opposed to separate branches for the CMS.

### CODE REVIEW

**Comment by TinBryn** [comment]
I'm fixing the merge conflicts locally. I will push this fix in a bit.

**Comment by TinBryn** [comment]
I can deploy it as a test, if all works we I will squash and merge.

**Comment by TinBryn** [comment]
I've seen that you are adding routes outside of the configureRoutes function that I setup specifically for adding new routes. I can fix that.

**Comment by danielgerardclaassen** [comment]
> 
> 
> I've seen that you are adding routes outside of the configureRoutes function that I setup specifically for adding new routes. I can fix that.

I was unsure of how the configureRoutes function would handle some of the asynchronicity of the security functions/calls. That is why I detached it. If you can manage to get it to work though, 👍

**Comment by danielgerardclaassen** [comment]
> 
> 
> > I've seen that you are adding routes outside of the configureRoutes function that I setup specifically for adding new routes. I can fix that.
> 
> I was unsure of how the configureRoutes function would handle some of the asynchronicity of the security functions/calls. That is why I detached it. If you can manage to get it to work though, 👍

I suppose testing on my local machine is different to testing on heroku, apologies for that

**Comment by TinBryn** [comment]
> I suppose testing on my local machine is different to testing on heroku, apologies for that

You can deploy branches to Heroku if you create an account and I add you as a collaborator.

**Comment by danielgerardclaassen** [comment]
> 
> 
> > I suppose testing on my local machine is different to testing on heroku, apologies for that
> 
> You can deploy branches to Heroku if you create an account and I add you as a collaborator.

I do have an account on Heroku, danielgerardclaassen@gmail.com if you don't mind. Though I am not aware of the collaboration systems they use

**Comment by TinBryn** [comment]
I will need to configure the SESSION_SECRET on the server, but it looks good otherwise

**Comment by danielgerardclaassen** [comment]
> 
> 
> I will need to configure the SESSION_SECRET on the server, but it looks good otherwise

Any idea how that will interface? We could very easily just keep a permanent secret.

**Comment by TinBryn** [comment]
> > I will need to configure the SESSION_SECRET on the server, but it looks good otherwise
> 
> Any idea how that will interface? We could very easily just keep a permanent secret.

It is done

**Pull request merged**
